apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
  labels:
    name: pod-volume
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
      - mountPath: /volume-dentro-container
        name: primeiro-volume

  - name: jenkins-container
    image: jenkins:alpine
  volumes:
    - name: primeiro-volume
      hostPath:
        path: /home/danilo/workspace_vs_code/volume-kubernetes
        type: Directory